### ISSUE TITLE
Pip broken

### ISSUE THREAD

**Issue by claygorman** [VojtechBartos/deepstream.io-client-python#1]
pip install deepstreamio_client doesnt seem to work

**Comment by VojtechBartos** [comment]
yeah, you are correct, i haven't actually have time to publish it in pypi so for now you have to install it via following command.

```sh
pip install git+https://github.com/VojtechBartos/deepstream.io-client-python.git#egg=deepstreamio_client
```

Also i have upgraded readme.

**Comment by VojtechBartos** [comment]
@claygorman submitted to Pypi. `pip install deepstreamio_client` is gonna work.
